# Generated by Django 4.1.1 on 2022-10-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('name', models.TextField(null=True)),
                ('photoUrl', models.TextField(default='https://lh3.googleusercontent.com/drive-viewer/AJc5JmSvH1nyYwDdbjl693wDu--xM8gZ7GB3O_lc47RmZNAe-JbZqNT-C2-ePtQzMIAzA9fty0bBvHs=w1366-h625', null=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('photoUrl', models.TextField()),
            ],
            options={
                'db_table': 'mentor',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('discount', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'promo',
            },
        ),
    ]
