# Generated by Django 4.1.1 on 2022-10-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('photoUrl', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.category')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.mentor')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('url', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.course')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.course')),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.course')),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
    ]
