# Generated by Django 4.1.1 on 2022-10-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_remove_material_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='job',
            field=models.TextField(default=''),
        ),
    ]
