# Generated by Django 4.1.1 on 2022-10-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_mentor_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='job',
            field=models.TextField(null=True),
        ),
    ]
