# Generated by Django 4.1.1 on 2022-10-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_alter_mentor_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
