# Generated by Django 4.1.1 on 2022-10-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_material_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='complete',
        ),
    ]
