# Generated by Django 4.1.1 on 2022-10-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_rename_question_project_feedback_course_project_ins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='project_ins',
            new_name='project_instruction',
        ),
    ]
