# Generated by Django 4.1.1 on 2022-10-29 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
