# Generated by Django 4.1.1 on 2022-10-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0013_project_created_at_project_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
